export type Term = { term: string; definition: string };

export const lexique: Term[] = [
  { term: "Sinistre", definition: "Événement imprévu couvert par le contrat d'assurance (accident, vol, incendie…)." },
  { term: "Garantie", definition: "Engagement de l'assureur à indemniser certains dommages, dans les limites du contrat." },
  { term: "Exclusion", definition: "Situation ou dommage expressément non couvert par le contrat." },
  { term: "Franchise", definition: "Somme restant à la charge de l'assuré après indemnisation." },
  { term: "Plafond d'indemnisation", definition: "Montant maximum que l'assureur versera pour un sinistre donné." },
  { term: "Prime", definition: "Cotisation payée par l'assuré en contrepartie de la couverture." },
  { term: "RC", definition: "Responsabilité Civile. Garantie obligatoire couvrant les dommages causés aux tiers." },
  { term: "COL", definition: "Dommages Collision : couvre le véhicule assuré en cas de choc avec un tiers identifié." },
  { term: "DOM", definition: "Dommages Tous Accidents : couvre le véhicule assuré même sans tiers identifié." },
  { term: "BDG", definition: "Bris de Glace : couvre les vitres du véhicule." },
  { term: "CID", definition: "Convention d'Indemnisation Directe. Accord entre compagnies marocaines pour harmoniser les responsabilités." },
  { term: "CG", definition: "Conditions Générales. Règles communes à tous les assurés d'un contrat." },
  { term: "CP", definition: "Conditions Particulières. Garanties, franchises et plafonds propres à un client." },
  { term: "PEC", definition: "Prise en Charge. Wafa règle directement le garage conventionné, le client ne paie que sa franchise." },
  { term: "WAFA Sarii", definition: "Procédure forfaitaire ultra-rapide pour les sinistres < 10 000 DH." },
  { term: "Expert", definition: "Professionnel habilité à évaluer les dommages et valider les réparations." },
  { term: "Laada", definition: "Expertise en ligne pour les dommages < 1 500 DH." },
  { term: "Vétusté", definition: "Perte de valeur d'un bien liée à son âge et son usure." },
  { term: "Valeur vénale", definition: "Valeur marchande du véhicule avant l'accident." },
  { term: "Valeur d'épave", definition: "Valeur du véhicule après l'accident (revente ferrailleur)." },
  { term: "Réforme économique", definition: "Prononcée quand les réparations dépassent 2/3 de la valeur vénale." },
  { term: "Réforme technique", definition: "Prononcée quand la structure ou la sécurité du véhicule sont atteintes." },
  { term: "Annexe 29", definition: "Déclaration officielle d'irréparabilité d'un véhicule." },
  { term: "SINMAT", definition: "Système interne Wafa de traçabilité des dossiers et appels." },
  { term: "MyWafa", definition: "Application client pour suivre son dossier en autonomie." },
  { term: "Constat amiable", definition: "Document formel rempli par les conducteurs pour décrire les circonstances d'un accident." },
];
