/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizFinalRouteImport } from './routes/quiz-final'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LexiqueRouteImport } from './routes/lexique'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as ModulesModuleIdIndexRouteImport } from './routes/modules.$moduleId.index'
import { Route as ModulesModuleIdQuizRouteImport } from './routes/modules.$moduleId.quiz'
import { Route as ModulesModuleIdLessonsLessonIdRouteImport } from './routes/modules.$moduleId.lessons.$lessonId'

const QuizFinalRoute = QuizFinalRouteImport.update({
  id: '/quiz-final',
  path: '/quiz-final',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiqueRoute = LexiqueRouteImport.update({
  id: '/lexique',
  path: '/lexique',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesModuleIdIndexRoute = ModulesModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesModuleIdRoute,
} as any)
const ModulesModuleIdQuizRoute = ModulesModuleIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ModulesModuleIdRoute,
} as any)
const ModulesModuleIdLessonsLessonIdRoute =
  ModulesModuleIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lexique': typeof LexiqueRoute
  '/modules': typeof ModulesRouteWithChildren
  '/quiz-final': typeof QuizFinalRoute
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/modules/$moduleId/lessons/$lessonId': typeof ModulesModuleIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lexique': typeof LexiqueRoute
  '/quiz-final': typeof QuizFinalRoute
  '/modules': typeof ModulesIndexRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/modules/$moduleId': typeof ModulesModuleIdIndexRoute
  '/modules/$moduleId/lessons/$lessonId': typeof ModulesModuleIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lexique': typeof LexiqueRoute
  '/modules': typeof ModulesRouteWithChildren
  '/quiz-final': typeof QuizFinalRoute
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/modules/$moduleId/lessons/$lessonId': typeof ModulesModuleIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lexique'
    | '/modules'
    | '/quiz-final'
    | '/modules/$moduleId'
    | '/modules/'
    | '/modules/$moduleId/quiz'
    | '/modules/$moduleId/'
    | '/modules/$moduleId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lexique'
    | '/quiz-final'
    | '/modules'
    | '/modules/$moduleId/quiz'
    | '/modules/$moduleId'
    | '/modules/$moduleId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/lexique'
    | '/modules'
    | '/quiz-final'
    | '/modules/$moduleId'
    | '/modules/'
    | '/modules/$moduleId/quiz'
    | '/modules/$moduleId/'
    | '/modules/$moduleId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LexiqueRoute: typeof LexiqueRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  QuizFinalRoute: typeof QuizFinalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz-final': {
      id: '/quiz-final'
      path: '/quiz-final'
      fullPath: '/quiz-final'
      preLoaderRoute: typeof QuizFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexique': {
      id: '/lexique'
      path: '/lexique'
      fullPath: '/lexique'
      preLoaderRoute: typeof LexiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$moduleId/': {
      id: '/modules/$moduleId/'
      path: '/'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof ModulesModuleIdIndexRouteImport
      parentRoute: typeof ModulesModuleIdRoute
    }
    '/modules/$moduleId/quiz': {
      id: '/modules/$moduleId/quiz'
      path: '/quiz'
      fullPath: '/modules/$moduleId/quiz'
      preLoaderRoute: typeof ModulesModuleIdQuizRouteImport
      parentRoute: typeof ModulesModuleIdRoute
    }
    '/modules/$moduleId/lessons/$lessonId': {
      id: '/modules/$moduleId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/modules/$moduleId/lessons/$lessonId'
      preLoaderRoute: typeof ModulesModuleIdLessonsLessonIdRouteImport
      parentRoute: typeof ModulesModuleIdRoute
    }
  }
}

interface ModulesModuleIdRouteChildren {
  ModulesModuleIdQuizRoute: typeof ModulesModuleIdQuizRoute
  ModulesModuleIdIndexRoute: typeof ModulesModuleIdIndexRoute
  ModulesModuleIdLessonsLessonIdRoute: typeof ModulesModuleIdLessonsLessonIdRoute
}

const ModulesModuleIdRouteChildren: ModulesModuleIdRouteChildren = {
  ModulesModuleIdQuizRoute: ModulesModuleIdQuizRoute,
  ModulesModuleIdIndexRoute: ModulesModuleIdIndexRoute,
  ModulesModuleIdLessonsLessonIdRoute: ModulesModuleIdLessonsLessonIdRoute,
}

const ModulesModuleIdRouteWithChildren = ModulesModuleIdRoute._addFileChildren(
  ModulesModuleIdRouteChildren,
)

interface ModulesRouteChildren {
  ModulesModuleIdRoute: typeof ModulesModuleIdRouteWithChildren
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesModuleIdRoute: ModulesModuleIdRouteWithChildren,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LexiqueRoute: LexiqueRoute,
  ModulesRoute: ModulesRouteWithChildren,
  QuizFinalRoute: QuizFinalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
